#include "pinout.h"

int START_SWITCH_PIN = 0;

int UART_BLUEPILL_TX_PIN = 0; 
int UART_BLUEPILL_RX_PIN = 0; 

//Front arm
int VACUUM_FRONT_MOTOR_PIN = 0;

int ZMOTOR_FRONT_CW_PIN = 0;
int ZMOTOR_FRONT_CCW_PIN = 0;
int ZMOTOR_FRONT_ENCODER_PIN = 0;
int ZMOTOR_FRONT_RETRACT_LIMIT_SWITCH_PIN = 0;

int RMOTOR_FRONT_FORWARD_PIN = 34;
int RMOTOR_FRONT_BACKWARD_PIN = 0;
int RMOTOR_FRONT_ENCODER_PIN = 9;
int RMOTOR_FRONT_RETRACT_LIMIT_SWITCH_PIN = 0;

int YMOTOR_FRONT_UP_PIN = 0;
int YMOTOR_FRONT_DOWN_PIN = 0;
int YMOTOR_FRONT_EXTEND_LIMIT_SWITCH_PIN = 0;
int YMOTOR_FRONT_RETRACT_LIMIT_SWITCH_PIN = 0;

//Back arm
int VACUUM_BACK_MOTOR_PIN = 0;

int ZMOTOR_BACK_CW_PIN = 0;
int ZMOTOR_BACK_CCW_PIN = 0;
int ZMOTOR_BACK_ENCODER_PIN = 0;
int ZMOTOR_BACK_RETRACT_LIMIT_SWITCH_PIN = 0;

int RMOTOR_BACK_FORWARD_PIN = 0;
int RMOTOR_BACK_BACKWARD_PIN = 0;
int RMOTOR_BACK_ENCODER_PIN = 0;
int RMOTOR_BACK_RETRACT_LIMIT_SWITCH_PIN = 0;

int YMOTOR_BACK_UP_PIN = 0;
int YMOTOR_BACK_DOWN_PIN = 0;
int YMOTOR_BACK_EXTEND_LIMIT_SWITCH_PIN = 0;
int YMOTOR_BACK_RETRACT_LIMIT_SWITCH_PIN = 0;
